### ISSUE TITLE
imagePullSecrets must be duplicated on every controller manifest

### ISSUE THREAD

**Issue by brantb** [weaveworks/flux#1043]
The [recommended approach to using `imagePullSecrets`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) is to attach them to a service account (usually `default`). This eliminates the need to duplicate the `imagePullSecret` on every controller that requires it.

However, this doesn't work with Flux today. Unless the controller explicitly specifies an `imagePullSecret`, Flux won't be able to poll its images.

I feel it would be much easier to add an imagePullSecret to the `flux` ServiceAccount like this:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: flux
  name: flux
imagePullSecrets:
  - name: my-private-registry
```
