### ISSUE TITLE
Automating a release removes custom annotations

### ISSUE THREAD

**Issue by sebastianroesch** [weaveworks/flux#1044]
I clicked on Automate in Weave Cloud, which created a new commit in my repository.

In this comment, the `flux.weave.works/automated: "true"` annotation was added to the service, but my custom annotations were removed.

This is the diff:

```
annotations:
-    prometheus.io/scrape: 'true'
-    prometheus.io/port: '9090'
+    flux.weave.works/automated: "true"
```

Please do not modify existing annotations but rather add the required ones.

**Comment by squaremo** [comment]
@sebastianroesch We do go to some trouble not to disturb existing annotations; but clearly, it is far from perfect :-( May we see the full file that was altered (redacted, if necessary)?

**Comment by sebastianroesch** [comment]
Sure, this is the (slightly redacted) file. The service has only two annotations, which were gone after automating the deployment.

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: usert-service-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service-v1
        task: user
        version: v1
    spec:
      containers:
      - name: user-service-v1
        image: user-service:latest-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /healthy
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthy
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 2
          failureThreshold: 5
      tolerations:
        - key:preemptible
          operator: Equal
          value: 'true'
          effect: NoSchedule
      imagePullSecrets:
        - name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-v1
    task: user
  name: user-service-v1
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  ports:
  - port: 80
    targetPort: 80
    name: api
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    app: user-service-v1
```
