### ISSUE TITLE
Indenting container blocks in template leads to erroneous updates

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1082]
If you indent the container blocks in a YAML like this:

```
containers:
  - name: foo
    image: foo:v1
  - name: bar
    image: bar:v1
```

then releasing, e.g., `foo:v2` will update the image field in _all_ the containers. The cause is that the regexp that breaks the spec up into containers does not account for the extra indentation, and treats the whole list of containers as one block; then, the replacement is done with "replace all".

Just changing the "replace all" with "replace" wouldn't help, because it would replace the first occurrence which might still be incorrect. Doing the replacement with the old image would be better, but might still fail to replace anything.

The only real solution (while staying with regexps) is to correctly separate the container blocks.

**Comment by 2opremio** [comment]
To be clear, this is mitigated by changing indentation to:

```
containers:
- name: foo
   image: foo:v1
- name: bar
   image: bar:v1
```

i.e:

```diff
--- a.yaml	2018-05-21 10:00:18.000000000 +0200
+++ b.yaml	2018-05-21 10:00:24.000000000 +0200
@@ -1,5 +1,5 @@
 containers:
-  - name: foo
-    image: foo:v1
-  - name: bar
-    image: bar:v1
+- name: foo
+  image: foo:v1
+- name: bar
+  image: bar:v1
```
