### ISSUE TITLE
Verifying CronJob fails

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1126]
If I put this is my test repository:

```
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: default
  name: weekly-curl-homepage
  annotations:
    weave.works.some-annotation: Just for fidelity
spec:
  # Here is a multiline comment
  # to replicate the origin YAML closely
  schedule: "5 18 * * 3"
  # Deleting jobs after they're done will clean up their 'Completed' pods,
  # thereby avoiding spurious PodNotReady alerts
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: weekly-curl-homepage
            image: centos:7 # Has curl installed by default
            imagePullPolicy: Always
            command:
            - /bin/curl
            args:
            - -X
            - GET
            - https://weave.works/
```

then I cannot update it.

First theory: it hits a corner case of ruamel (the python YAML parser in kubeyaml), which mangles it. But

```
./bin/kubeyaml image --namespace default --kind CronJob --name weekly-curl-homepage --container weekly-curl-homepage --image centos:foo < cronjob.yaml
```

outputs the result just fine.

Second theory: we're parsing or interpreting the manifest wrong in `cluster/kubernetes/resource/cronjob.go` -- yet to test this.
