### ISSUE TITLE
Support FluxHelmRelease values format with more than one image

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1175]
At present fluxd knows how to interpret and update FluxHelmRelease manifests that use the format

```
values:
  image: repo/image:tag
```

which admits only pretty simple charts, since it only lets you change one image. An improvement would be

```
values:
  foo:
    image: repo/foo:tag
  bar:
    image: repo/bar:tag
```

where each image is under a label, which can be treated as the "container" for that image (most likely that's what the templates will use the values for).
