### ISSUE TITLE
CRDs do not get past Flux's Resource ID validation in Kubernetes 1.8.x 

### ISSUE THREAD

**Issue by hiddeco** [weaveworks/flux#1195]
**Flux version:** `1.4.1`
**Kubernetes version:** `1.8.12`

Given we let Flux manage a `CustomResourceDefinition` with the following contents:

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
 name: sealedsecrets.bitnami.com
spec:
 group: bitnami.com
 names:
   kind: SealedSecret
   listKind: SealedSecretList
   plural: sealedsecrets
   singular: sealedsecret
 scope: Namespaced
 version: v1alpha1
```

The resource ID that Flux attempts to create does not get past Flux's Resource ID validation because it contains multiple dots which is not defined in the regex. 

https://github.com/weaveworks/flux/blob/dee214421131582ae1d50e62fc4035c878e73d6b/flux.go#L16-L18

`ts=2018-07-03T10:25:39.590101769Z caller=loop.go:89 component=sync-loop err="executing HTTP request: 400 Bad Request parsing default:customresourcedefinition/sealedsecrets.bitnami.com: invalid service ID\n`

I think the regex(es) should be changed from `a-zA-Z0-9_-` to `a-zA-Z0-9_-.`.

**Side note:** I did not see this error in a K8S `1.1.x` cluster with the same CRD. Which makes me wonder if (and why) this is version related.
