### ISSUE TITLE
Chart release failed: heavy-pigeon: context.deadlineExceededError{}

### ISSUE THREAD

**Issue by konfiot** [weaveworks/flux#1233]
Okay, now i've managed to install and to sync flux helm with my private git repo
I've tried a simple installation of sonarqube, got the release with helm fetch --untar directly in the git helm charts repo
But now i've got the following error from the operator logs : 
```
ts=2018-07-16T11:54:55.16597311Z caller=operator.go:171 component=operator debug="PROCESSING item [\"sonarqube/heavy-pigeon\"]"
ts=2018-07-16T11:54:55.166004052Z caller=operator.go:228 component=operator debug="Starting to sync cache key sonarqube/heavy-pigeon"
ts=2018-07-16T11:55:00.476575709Z caller=status.go:75 component=annotator err="context deadline exceeded"
ts=2018-07-16T11:55:00.62039208Z caller=release.go:154 component=release info="releaseName= heavy-pigeon, action=CREATE, install options: {DryRun:false ReuseName:false}"
ts=2018-07-16T11:55:05.6330603Z caller=release.go:196 component=release error="Chart release failed: heavy-pigeon: context.deadlineExceededError{}"
ERROR: logging before flag.Parse: E0716 11:55:05.633180       7 operator.go:219] error syncing 'sonarqube/heavy-pigeon': context deadline exceeded
```
Here is the yaml file describing the release : 
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: sonarqube
  namespace:  sonarqube
  labels:
    chart: sonarqube
spec:
  chartGitPath: sonarqube
  releaseName: heavy-pigeon
```
