### ISSUE TITLE
Annotations and automated version upgrades 

### ISSUE THREAD

**Issue by stephenmoloney** [weaveworks/flux#1256]
### ***Issue Description:***

The annotations are not behaving as I had expected.

Here is my directory structure for the `releases` directory:

```
releases
|-- app.yaml
|-- cert-issuer.yaml
|-- cert-manager.yaml
|-- contour.yaml
|-- database.yaml
`-- flux.yaml
```

#### ***app.yaml*** is as follows:

```
---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: app
  namespace: develop
  labels:
    chart: app
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.app: glob:master-*
spec:
  chartGitPath: app
  releaseName: app
  values:
    image: <my_private_registry>/app:master-de3730af
```

#### ***cert-manager.yaml*** is as follows:

```
---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    chart: cert-manager
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.cert-manager: glob:v0.*.*
spec:
  chartGitPath: cert-manager
  releaseName: cert-manager
  values:
    image: quay.io/jetstack/cert-manager-controller:v0.4.0
```

***Problem 1:***
Despite cert-manager having the annotation `flux.weave.works/automated: "false"`, it is still
being updated.

***Problem 2:***
For cert-manager, I expected the annotation `flux.weave.works/tag.cert-manager: glob:v0.*.*` to only
update those tags corresponding to `v0.X.Y` but as can be seen in the image below, the updates are for a canary release (which does not correspond with `v0.*.*`):

![image](https://user-images.githubusercontent.com/12668653/43262721-0fcb6e76-90d9-11e8-9f98-1f828758d8e6.png)

Is there something wrong with the way I have tagged it? 

Flux version: `master-dfcfd33`
FluxHelmOperator version: `master-dfcfd33`
