### ISSUE TITLE
Respect requirements.yaml in helm operator

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1278]
Charts can come with dependencies: https://docs.helm.sh/developing_charts/#chart-dependencies

I believe the Helm CLI deals with these dependencies -- either downloading the charts from the repository given, or grabbing them from the fileystem before sending to Tiller.

We should come up with a sensible way to let people use the dependency management with the helm operator.

**Comment by ahmadiq** [comment]
+1 We're facing this issue as well. We'd like for the chart dependencies in the requirements.yaml to be downloaded automatically. At the moment we're providing a reference to the public chart repository in the requirements.yaml but that doesn't download, and we seem to need to include the chart within our flux release repo.

requirements.yaml snippet:
```
dependencies:

- name: prometheus
  version: 1.0.19
  repository: https://stakater.github.io/stakater-charts
  alias: prometheus

- name: grafana
  version: 1.0.31
  repository: https://stakater.github.io/stakater-charts  
  alias: grafana
```
