### ISSUE TITLE
documentation for annotations is missing

### ISSUE THREAD

**Issue by tompson** [weaveworks/flux#1337]
I had to ask in the #flux slack channel to get information about possible annotations for deployment automations like

```
annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.containername: semver:~0.4
```

nobody could find any documentation about possible annotations

**Comment by leoblanc** [comment]
@stefanprodan @tompson Hello, I have the same problem. It's not clear to me what the "containername" exactly means, since we are referring to Docker images tags. Is it the docker repo name? Is it the pod name? Something else? Automated image upgrades are not working for me (even using a public repo without authentication) but I guess that it's a configuration issue. Thank you very much.

**Comment by rndstr** [comment]
> It's not clear to me what the "containername" exactly means, since we are referring to Docker images tags.

It is the name of the container as defined in the YAML. Given the following example:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foobar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: foo
    spec:
      containers:
      - name: foo
        image: nginx:latest
      - name: bar
        image: nginx:latest
```
The containers are `foo` and `bar`.
```
flux.weave.works/tag.foo: semver:~0.4
flux.weave.works/tag.bar: glob:master-*
```
