### ISSUE TITLE
init containers are not updated

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/flux#1371]
If the init container image is not present in containers Flux will not update it.

Different images (the busybox never gets updated):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      initContainers:
      - name: init
        image: busybox:1.25
        command:
        - sleep
        - "1"
      containers:
      - name: podinfod
        image: quay.io/stefanprodan/podinfo:1.2.0
        command:
        - ./podinfo
        - --port=9898
        ports:
        - name: http
          containerPort: 9898
```
