### ISSUE TITLE
Publish fluxctl Linux packages

### ISSUE THREAD

**Issue by dholbach** [weaveworks/flux#1377]
It'd be great to have `fluxctl` packages for Linux distributed without having to go download a binary (and chmod) or build from source.

A similar discussion came up in the `eksctl` project recently (https://github.com/weaveworks/eksctl/issues/215) and I snaps, as they're supported on a variety of Linux flavours and the build ties in with our CI easily (only one additional yaml required).

Unfortunately are builds for both `fluxctl` and `eksctl` currently blocked on access to .dotfiles, but a strawman solution was just brought up to remedy this: https://github.com/snapcore/snapd/pull/5845

**Comment by dholbach** [comment]
> I am happy to provide an AUR package for Arch Linux based systems.

Sure. Why not? :-)

**Comment by guilhem** [comment]
!!! I didn't see it was solved !!! \o/
For your bug on version, I answered on launchpad about `version-script:` metadata you can put.
Maybe try with a `git describe` without `--dirty`

**Comment by guilhem** [comment]
You may also put all `$HOME/.kube` folder as personal-files.
Sometime I use CRT not inline or split config file into multiples.

**Comment by dholbach** [comment]
Probably not the prettiest solution, but the version string I fixed now thanks to your suggestion.

I can't seem to add all of `$HOME/.kube` to `personal-files`. That's a blocker for a snap then, right?

Current `snapcraft.yaml`:

```yaml
name: fluxctl
version-script: |
  FLUX_TAG="$(git tag -l | egrep -v '^(chart-|helm-|master-|pre-split)' | tail -n1)"
  if [ "$SNAPCRAFT_PROJECT_GRADE" = "stable" ]
  then
    echo $FLUX_TAG
  else
    GIT_REV="$(git rev-parse --short HEAD)"
    echo "$FLUX_TAG+$GIT_REV"
  fi
version: git
summary: fluxctl talks to Weave Flux and helps you deploy your code
description: |
  fluxctl talks to your Weave Flux instance and exposes all its
  functionality to an easy to use command line interface.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
plugs:
  personal-files:
    read:
      - $HOME/.kube/config
      - $HOME/.minikube/client.key
      - $HOME/.minikube/client.crt
      - $HOME/.minikube/ca.crt

parts:
  fluxctl:
    plugin: go
    go-importpath: github.com/weaveworks/flux
    prime:
      - bin/fluxctl

apps:
  fluxctl:
    command: fluxctl
    plugs: [personal-files, network, network-bind]
```

**Comment by dholbach** [comment]
This is working for me now:

```console
sudo snap install snapcraft --classic
sudo snap install multipass --beta --classic
snapcraft
```

With this `snapcraft.yaml` file:

```yaml
name: fluxctl
version-script: |
  FLUX_TAG="$(git tag -l | egrep -v '^(chart-|helm-|master-|pre-split)' | sort -n | tail -n1)"
  if [ "$SNAPCRAFT_PROJECT_GRADE" = "stable" ]
  then
    echo $FLUX_TAG
  else
    GIT_REV="$(git rev-parse --short HEAD)"
    echo "$FLUX_TAG+$GIT_REV"
  fi
version: git
summary: fluxctl talks to Weave Flux and helps you deploy your code
description: |
  fluxctl talks to your Weave Flux instance and exposes all its
  functionality to an easy to use command line interface.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic
base: core18

parts:
  fluxctl:
    source: .
    plugin: go
    go-importpath: github.com/weaveworks/flux
    override-pull: |
      snapcraftctl pull
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      export PATH=$GOPATH/bin:$PATH
      cd $GOPATH/src/github.com/weaveworks/flux
      dep ensure
    build-packages:
      - gcc
      - go-dep
    prime:
      - bin/fluxctl

apps:
  fluxctl:
    command: bin/fluxctl
```
