### ISSUE TITLE
Specify Tag Filter Policies as Code

### ISSUE THREAD

**Issue by pcfens** [weaveworks/flux#1409]
Is there a way to specify image tag filter policies in the control repository? I've only been able to find how to completely [ignore a deployment ](https://github.com/weaveworks/flux/blob/master/site/faq.md#can-i-temporarily-make-flux-ignore-a-deployment) through an annotation. If it is, then I'm happy to try and put a PR together to update some documentation after I figure out how to use it.

If it's not already a feature, the ability specify the equivalent of `fluxctl policy --controller=default:deployment/helloworld --tag-all='prod-*'` in the git repository that creates `deployment/helloworld` would be a welcome addition to an already great tool.

**Comment by stefanprodan** [comment]
Here is an example with regex, sem ver and glob tag filters:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regex:^1.*
    flux.weave.works/tag.main: semver:~1.2
    flux.weave.works/tag.sidecar: glob:dev-*
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: busybox:1.25
      containers:
      - name: main
        image: quay.io/stefanprodan/podinfo:1.2.0
      - name: sidecar
        image: quay.io/stefanprodan/podinfo:dev-kb9lm91e
```
