### ISSUE TITLE
"has different set of containers after update"

### ISSUE THREAD

**Issue by whereismyjetpack** [weaveworks/flux#1454]
Hello! I'm trying to run `--update-image` on a `FluxHelmRelease` and i'm getting the following error message:

```Error: verifying changes: failed to verify changes: resource "releasename" has different set of containers after update```

here is a redacted version of my FluxHelmRelease

```apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: greatapp-feature-flux
  namespace: default
  labels:
    chart: chart
  annotations:
    flux.weave.works/automated: "false"
spec:
  chartGitPath: chart
  releaseName: greatapp-feature-flux
  values:
    image:
      repository: nexus.company.foo.bar:5000/namespace/greatapp
      tag: e6e9d3a5ab1869ca0595eda1024985f100b68652
    ingress:
      hosts:
      - host.tld.foo
    externalSecret: "true"
```

the command i'm running that emits the error is as follows

```
fluxctl release -n default --controller=default:fluxhelmrelease/greatapp-feature-flux --update-image=nexus.company.foo.bar:5000/group/greatapp:f87b7f7bb25f1bc5e98f4da4d480e87f4f72c55b```

**Comment by whereismyjetpack** [comment]
More info:

if i change the chart, and values to support 

```
image: foo.bar.baz:5000:version
```

things seem to work fine. its not hard to change, but 

```
image:
  repository: foo
  tag: bar
  pullPolicy: Always
```

is a pretty common format, since it's what's spit out when running `helm create`

**Comment by whereismyjetpack** [comment]
Is there anything I can do to help? Thanks!

**Comment by squaremo** [comment]
Sorry, did not see this one go past last week :-S

The release code is supposed to handle the format

```
# ... other stuff
spec:
  values:
    image:
      repository: foo.bar.baz/image
      tag: version
```

If I take the example above, add the `apiVersion` field, and change the image repository to `weaveworks/hello-world` (so that it won't balk at the image not existing), I can do a successful `fluxctl release`.

The file update code tries very hard to preserve comments and formatting in the file by using a round-tripping YAML library. The particular library (ruamel, in Python) has some bugs hidden it the corners. That's one of the reasons flux does the verification that's causing you problems -- it's better to refuse to push the commit, than to push garbage.

Anyway. I suspect that the un-redacted file may be provoking one of the bugs in the YAML parser. You can see what it's doing by running it (or rather, the file update helper) yourself:

```
docker run --rm -i quay.io/squaremo/kubeyaml:0.4.2 annotate \
  --namespace default --kind FluxHelmRelease --name greatapp-feature-flux \
    foo=bar < /path/to/file.yaml
```

**Comment by squaremo** [comment]
In the case that you have an image defined at the top level, use `--container=chart-image`. Not obvious!

**Comment by whereismyjetpack** [comment]
with the image i just get "manifest not found" i'm not sure what i'm doing wrong :(

**Comment by squaremo** [comment]
You may be on to something there. If I put the YAML from above in a file /tmp/fhr.yaml, then do this:

```
docker run --rm -i quay.io/squaremo/kubeyaml:0.5.0 image --namespace default --kind FluxHelmRelease --name greatapp-feature-flux --container chart-image --image nexus.company.foo.bar:5000/namespace/greatapp:acb123 < /tmp/fhr.yaml
```

I get the output

```
---
kind: FluxHelmRelease
metadata:
  name: greatapp-feature-flux
  namespace: default
  labels:
    chart: chart
  annotations:
    flux.weave.works/automated: "false"
spec:
  chartGitPath: chart
  releaseName: greatapp-feature-flux
  values:
    image:
      repository: nexus.company.foo.bar:5000/namespace/greatapp:acb123
      tag: ''
    ingress:
      hosts:
      - host.tld.foo
    externalSecret: "true"
```

NB the repository and tag values being wrong. The missing tag may lead to fluxd to not recognise it as a "container", and therefore the verification error.
