### ISSUE TITLE
HTTP Proxy not used when connecting with remote GIT repository

### ISSUE THREAD

**Issue by demikl** [weaveworks/flux#1535]
Pods in my environment don't have direct access to Internet resources, they have to use a proxy. So, for `flux-helm-operator`, the deployment manifest contains these environments variables:

```
          env:
            - name: HTTP_PROXY
              value: http://proxy.internalorg:80
            - name: http_proxy
              value: http://proxy.internalorg:80
            - name: HTTPS_PROXY
              value: http://proxy.internalorg:80
            - name: https_proxy
              value: http://proxy.internalorg:80
            - name: NO_PROXY
              value: 127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.internalorg,...
            - name: no_proxy
              value: 127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.internalorg,....
```

Whenever I'm creating a HelmRelease object (using v0.5.0) specifying an external (github) GIT repository, those proxy env variables are not used:

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: cluster-tools
  labels:
    chart: consul
spec:
  chart:
    git: https://github.com/hashicorp/consul-helm.git
    path: "/"
    ref: "v0.3.0"
  releaseName: consul
```

Logs from `flux-helm-operator`:
```
ts=2018-11-20T10:11:32.776998797Z caller=chartsync.go:243 component=chartsync info="Start of releasesync"
ts=2018-11-20T10:11:32.803799336Z caller=chartsync.go:318 component=chartsync info="chart repo not ready yet" releaseName=consul resource=cluster-tools:HelmRelease/consul status=new err="git clone --mirror: fatal: unable to access 'https://github.com/hashicorp/consul-helm.git/': Could not resolve host: github.com"
```

The `Could not resolve host: github.com` is an indicator that the proxy is not used since DNS resolution should not occur on the client side, but on the proxy. When I manually call `git clone...` from within the pod (using `kubectl exec -ti ... sh`), it works fine since environment variables are set.

My guess is that the `git` command is launched within the operator without retrieving environment variables:
https://github.com/weaveworks/flux/blob/8f09ae615bc9e12e34567d5bd6e1505998c1f608/git/operations.go#L268

Maybe something like `c.Env = os.Environ()` might work ?
