### ISSUE TITLE
Be able to fetch helm charts via proxy

### ISSUE THREAD

**Issue by davidkarlsen** [weaveworks/flux#1625]
```
1T00:35:58.006250504Z caller=chartsync.go:340 component=chartsync info="chart download failed" releaseName=ode-problem-detector resource=node-problem-detector:helmrelease/node-problem-detector err="Looks like \"https://kubernetes-charts.storage.googleapis.com\" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 216.58.207.240:443: connect: connection timed out"
```
I have deployed the helmOperator via helm with values:
``` 
helmOperator:
  create: true
  repository: mycorpdockerregistry:8085/weaveworks/helm-operator
  extraEnvs:
  - name: HTTP_PROXY
    value: http://mycorp_outbound_proxy:8080
  - name: HTTPS_PROXY
    value: http://mycorp_outbound_proxy:8080
  - name: NO_PROXY
    value: .......,tiller-deploy.kube-system
```
