### ISSUE TITLE
helm operator: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by florianrusch** [weaveworks/flux#1637]
I'm trying to pull a helm chart from a private registry with a self-signed certificate.
Now the helm operator logs this message:
```
ts=2019-01-08T12:13:18.11620482Z caller=chartsync.go:244 component=chartsync info="Start of releasesync"
ts=2019-01-08T12:13:18.173598161Z caller=chartsync.go:340 component=chartsync info="chart download failed" releaseName=umbrella resource=dev:helmrelease/umbrella err="Looks like \"https://helm.example.com/chartrepo/test\" is not a valid chart repository or cannot be reached: Get https://helm.example.com/chartrepo/test/index.yaml: x509: certificate signed by unknown authority"
ts=2019-01-08T12:13:18.173670137Z caller=chartsync.go:249 component=chartsync info="End of releasesync"
```

I've already tried to set the `repository.yaml` as [here](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#authentication-for-helm-repos) described:

```
repositories:
- caFile: ""
  cache: helm-test-index.yaml
  certFile: ""
  keyFile: ""
  name: helm-test
  password: xxx
  url: https://helm.example.com/chartrepo/test
  username: xxx
```

Does someone know whats wrong or what I've missed?
