### ISSUE TITLE
flux chokes on unavailable image from registry

### ISSUE THREAD

**Issue by thanhnl** [weaveworks/flux#1701]
Using redis example from https://github.com/weaveworks/flux-get-started
Run `fluxctl list-images`, flux shows problem with this image:

```
demo:helmrelease/redis              chart-image         quay.io/bitnami/redis             image data not available
demo:statefulset/redis-master       redis               docker.io/quay.io/bitnami/redis   image data not available
```

fluxd log:

```
ts=2019-02-01T08:48:30.213333357Z caller=warming.go:313 component=warmer canonical_name=index.docker.io/bitnami/redis auth={map[]} err="manifest unknown: manifest unknown" ref=bitnami/redis:4.0.8-r3
ts=2019-02-01T08:48:30.21484334Z caller=warming.go:364 component=warmer updated=bitnami/redis successful=0 attempted=1
```

Examine manifest from docker hub for this specific tag:

```
curl -s -H "Authorization: Bearer ${TOKEN}" https://index.docker.io/v2/bitnami/redis/manifests/4.0.8-r3                                                             
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"bitnami/redis","Revision":"sha256:9c7f4a0958280a55a4337d74c22260bc338c26a0a2de493a8
ad69dd73fd5c290"}}]}
```

![tag](https://user-images.githubusercontent.com/1477165/52112902-83a38080-263a-11e9-83d8-1844ba193ac5.jpg)

**Comment by thanhnl** [comment]
I did these steps:
- Disable automate
- Deploy with tag 5.0.2
- Enable automate

It's not upgraded to 5.0.3 

HelmRelease content:
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: devops
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~5.0
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 5.1.3
  valueFileSecrets:
    # the redis-auth secret contains the password value
  - name: redis-auth
  values:
    usePassword: true
    image:
      repository: bitnami/redis
      tag: "5.0.2"
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: false
    master:
      securityContext:
        enabled: false
        fsGroup: 0
        runAsUser: 0
      persistence:
        enabled: false
```
