### ISSUE TITLE
Current Flux Helm release missing repository authentication options

### ISSUE THREAD

**Issue by timwebster9** [weaveworks/flux#1706]
The docs [here](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#authentication-for-helm-repos) say you can configure authentication for a Helm repository by mounting a volume:
```
      {{- if .Values.helmOperator.configureRepositories.enable }}
      - name: {{ .Values.helmOperator.configureRepositories.volumeName | quote }}
        secret:
          secretName: {{ .Values.helmOperator.configureRepositories.secretName | quote }}
      - name: {{ .Values.helmOperator.configureRepositories.cacheVolumeName | quote }}
        emptyDir: {}
      {{- end }}
```

however the latest published chart doesn't appear to include this functionality.  Opening up the template `helm-operator-deployment.yaml` from the 0.6.0 tarball you can see it's missing:

```
      volumes:
      {{- if .Values.ssh.known_hosts }}
      - name: sshdir
        configMap:
          name: {{ template "flux.fullname" . }}-ssh-config
          defaultMode: 0600
      {{- end }}
      - name: git-key
        secret:
          {{- if .Values.helmOperator.git.secretName }}
          secretName: {{ .Values.helmOperator.git.secretName }}
          {{- else if .Values.git.secretName }}
          secretName: {{ .Values.git.secretName }}
          {{- else }}
          secretName: {{ template "flux.fullname" . }}-git-deploy
          {{- end }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.enable }}
      - name: helm-tls-certs
        secret:
          secretName: {{ .Values.helmOperator.tls.secretName }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.verify }}
      - name: helm-tls-ca
        configMap:
          name: {{ template "flux.fullname" . }}-helm-tls-ca-config
          defaultMode: 0600
      {{- end }}
      {{- end }}
```

So not sure what's going on here?  Should we clone this repo and install the chart that way?  Or do you not publish charts when merging to master?  What do you recommend?
