### ISSUE TITLE
 SERVER_ERROR object too large for cache

### ISSUE THREAD

**Issue by montyz** [weaveworks/flux#1720]
I notice these `SERVER_ERROR object too large for cache` messages in my logs. Surrounding messages provided for context:
```
ts=2019-02-08T23:28:02.691831547Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
ts=2019-02-08T23:28:07.910472747Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
ts=2019-02-08T23:28:13.118912514Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
ts=2019-02-08T23:28:20.898754563Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
ts=2019-02-08T23:28:23.726442295Z caller=images.go:128 component=cluster resource=sftp:deployment/sftp err="getting secret \"myregistrykey\" from namespace \"sftp\": secrets \"myregistrykey\" not found"
ts=2019-02-08T23:28:26.108687709Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
ts=2019-02-08T23:28:29.117995084Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-02-08T23:28:29.153912177Z caller=memcached.go:133 component=memcached err="storing in memcache: memcache: unexpected response line from \"set\": \"SERVER_ERROR object too large for cache\\r\\n\""
ts=2019-02-08T23:28:29.153977173Z caller=warming.go:185 component=warmer canonical_name=index.docker.io/larktech/goldfinch auth="{map[index.docker.io:<registry creds for larkbuildmachine@index.docker.io, from yoni:secret/myregistrykey>]}" err="writing result to cache: memcache: unexpected response line from \"set\": \"SERVER_ERROR object too large for cache\\r\\n\""
ts=2019-02-08T23:28:30.29245483Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-02-08T23:28:32.542390094Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
ts=2019-02-08T23:28:32.542452133Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-02-08T23:28:36.525463416Z caller=loop.go:100 component=sync-loop event=refreshed url=git@dev-gogs-ssh.lark.com:larktech/dev8a-cluster branch=master HEAD=af4b2c59d33aeff278ae855d1004688156101e54
```

Any idea what this might be about?

**Comment by stefanprodan** [comment]
Looks like the image metadata goes over the default limit. You could set `memcached. maxItemSize=5m` and see if it's enough.  https://github.com/weaveworks/flux/pull/1453

**Comment by 2opremio** [comment]
@montyz did you get a chance to raise the limit and see if it fixes it?

**Comment by 2opremio** [comment]
Tentatively setting this as `bug` since the default `maxItemSize` may be too small and require reconsideration. 

@montyz assuming that the item size was the culprit, it would be good if you could give us some further information about the image metadata, to understand whether we should change the default value

**Comment by montyz** [comment]
I was using the straight k8s deployment so I added this `-I` arg to the memcached args:

```
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 64    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -I 5m
        # - -vv    # Uncomment to get logs of each request and response.
        ports:
        - name: clients
          containerPort: 11211
```

It took about 10 min but it was able to fetch all the metadata. We have one docker repo with 3241 tags, maybe that was what didn't fit? I don't know what else you might want to know about the image metadata.
