### ISSUE TITLE
helm operator not updating release from chart stored in git

### ISSUE THREAD

**Issue by j18e** [weaveworks/flux#1722]
I've released a chart using flux/helm-operator to my cluster from a chart in my enonic-xp git repo (pointing  at master). Upon updating the chart itself, however, the helm operator does not pick up on my update.

The logs from helm-operator don't seem to notice that the chart source has diverged from what's running in the cluster.
```ts=2019-02-11T08:44:31.69388553Z caller=release.go:139 component=release info="processing release bc-minside-test-temp" action=CREATE options="{DryRun:true ReuseName:false}" timeout=300s```

As I understand, the operator is meant to keep up with the ref of any charts coming from git repos. My HelmRelease is below.

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mysite
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:*
spec:
  releaseName: mysite
  chart:
    git: https://github.com/j18e/enonic-xp.git
    ref: master
    path: charts/enonic-xp
  values:
    image: j18e/enonic-xp:8bba580
```
