### ISSUE TITLE
Flux doesn't update all images of a HelmRelease when all images changes with the same id

### ISSUE THREAD

**Issue by cazzoo** [weaveworks/flux#1738]
I'm facing a really annoying issue while having flux to do automated releases of my helm release.

I have a buch of releases on my repository, and for every of them I have at least 2 images.
When updating code of my given application, i'm pushing a docker images to my repo (all images of the given helmRelease) and I'm expecting that flux does understand that all images have the same version number.
I reality, Flux does update only the first image of the helmRelease and not all of them, which creates inconsistency for the CD.

Here is a small example : 

Helm release before pushing code:
```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dashboard
  namespace: staging
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.chart-image: glob:snapshot-*
spec:
  chart:
    name: dashboard
    repository: https://myrepo/repository/helm-hosted/
    version: 2019.2.0-SNAPSHOT
  values:
    replicaCount: 3
    image:
      repository: myrepo:5001/docker/dashboard-runtime
      tag: snapshot-d013788
      pullPolicy: Always
    configurationLoader:
      repository: myrepo:5001/docker/dashboard-configuration-loader
      tag: snapshot-d013788
      pullPolicy: Always
    loader:
      repository: myrepo:5001/docker/dashboard-database-loader
      tag: snapshot-d013788
      pullPolicy: Always
```

My CI (jenkins) builds dashboard app and push docker images for dashboard-runtime, dashboard-configuration-loader and dashboard-database-loader with this tag : **snapshot-67e3ca2**

Helm release updated by flux:
```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dashboard
  namespace: staging
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.chart-image: glob:snapshot-*
spec:
  chart:
    name: dashboard
    repository: https://myrepo/repository/helm-hosted/
    version: 2019.2.0-SNAPSHOT
  values:
    replicaCount: 3
    image:
      repository: myrepo:5001/docker/dashboard-runtime
      tag: snapshot-67e3ca2
      pullPolicy: Always
    configurationLoader:
      repository: myrepo:5001/docker/dashboard-configuration-loader
      tag: snapshot-d013788
      pullPolicy: Always
    loader:
      repository: myrepo:5001/docker/dashboard-database-loader
      tag: snapshot-d013788
      pullPolicy: Always
```

You can see the tag for dashboard-configuration-loader and dashboard-database-loader hasn't been updated properly.

Any idea how to fix/workaround that issue ?

**Comment by oldskool** [comment]
It just looks like you're missing the annotations for the other 2 containers. Based on your HelmRelease, I'd expect these annotations:

```yaml
flux.weave.works/tag.image: glob:snapshot-*
flux.weave.works/tag.configurationLoader: glob:snapshot-*
flux.weave.works/tag.loader: glob:snapshot-*
```

**Comment by 2opremio** [comment]
After a quick look at the code I think Flux should recognize those containers. I will look into this more deeply, but before that,  can you confirm that :

1. You configured flux to release the image of all the containers automatically (not just the first one).
2. You didn't mark any of the containers as locked in flux


Some other relevant info:
* Has this ever worked for you or did it break recently?
* Can you share the logs?

**Comment by 2opremio** [comment]
Thanks @oldsckool!

**Comment by stefanprodan** [comment]
The `flux.weave.works/automated: true` annotation should be enough to trigger updates for all images. The sem ver is just a filter, the update should work without it. I think this is a bug in Flux or in https://github.com/squaremo/kubeyaml

**Comment by oldskool** [comment]
@stefanprodan Then I must've misunderstood the FAQ "My Helm charts have more than one container image. How can I automate the image tag update for all my containers?" of your [blog article](https://www.weave.works/blog/managing-helm-releases-the-gitops-way), which uses a similar example as my earlier post:

```yaml
annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.prometheus: semver:~2.3
    flux.weave.works/tag.alertmanager: glob:v0.15.*
    flux.weave.works/tag.nats: regexp:^0.6.*
```

I think the situation here is the same?

**Comment by stefanprodan** [comment]
The situation is different, in my example all images have names, while here only the last two are named images. I'm guessing that `flux.weave.works/tag.chart-image` restricts the update to the first image.

**Comment by 2opremio** [comment]
After reading
https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux
carefully and taking a look at the code, I found the problem.

The last two containers are missing an `image:` key, which prevents Flux
from detecting them:

That is:

```
  values:
    replicaCount: 3
    image:
      repository: myrepo:5001/docker/dashboard-runtime
      tag: snapshot-d013788
      pullPolicy: Always
    configurationLoader:
      image:
        repository: myrepo:5001/docker/dashboard-configuration-loader
        tag: snapshot-d013788
      pullPolicy: Always
    loader:
      image:
        repository: myrepo:5001/docker/dashboard-database-loader
        tag: snapshot-d013788
      pullPolicy: Always
```

On top of that, for consistency, I would recommend not using the anonymous,
top-level container declaration (implicitly called `chart-image`):

```
  values:
    replicaCount: 3
    runtime:
      image:
        repository: myrepo:5001/docker/dashboard-runtime
        tag: snapshot-d013788
      pullPolicy: Always
    configurationLoader:
      image:
        repository: myrepo:5001/docker/dashboard-configuration-loader
        tag: snapshot-d013788
      pullPolicy: Always
    loader:
      image:
        repository: myrepo:5001/docker/dashboard-database-loader
        tag: snapshot-d013788
      pullPolicy: Always
```

On top of that, and as suggested before, it seems like all the containers
could also use a glob filter. That is:

```
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.chart-image: glob:snapshot-*
    flux.weave.works/tag.configurationLoader: glob:snapshot-*
    flux.weave.works/tag.loader: glob:snapshot-*
```

or

```
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.runtime: glob:snapshot-*
    flux.weave.works/tag.configurationLoader: glob:snapshot-*
    flux.weave.works/tag.loader: glob:snapshot-*
```

(if you take my recommendation of not using the anonymous toplevel
`chart-image` container)
