### ISSUE TITLE
flux can't upgrade image

### ISSUE THREAD

**Issue by thanhnl** [weaveworks/flux#1747]
#### What you expected to happen?

Flux auto upgrade container to newer image.

#### How to reproduce it?

I did these steps:
- Disable automate
- Deploy with tag 5.0.2
- Enable automate

It's not upgraded to 5.0.3 

HelmRelease content:
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: devops
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~5.0
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 5.1.3
  valueFileSecrets:
    # the redis-auth secret contains the password value
  - name: redis-auth
  values:
    usePassword: true
    image:
      repository: bitnami/redis
      tag: "5.0.2"
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: false
    master:
      securityContext:
        enabled: false
        fsGroup: 0
        runAsUser: 0
      persistence:
        enabled: false
```

#### version

flux chart: 0.6.3
flux: 1.10.1
helm operator: 0.6.0
