### ISSUE TITLE
`automated` and `ignore` annotations clash

### ISSUE THREAD

**Issue by whitlaaa** [weaveworks/flux#1748]
Having a resource annotated as both automated and ignored appears to be treated as both and seems to break automation of all cluster resources.

In our case, as long as we had some HelmRelease manifests annotated with both, none of the automated resources in our cluster were getting their images updated. Note that we were seeing the latest images available (via `fluxctl list-images`), they were just never used.

Upon removing one of the two, everything started flowing as normal.

One of our HelmReleases looked like this:

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: my-webapi
  namespace: default
  labels:
    chart: webapi
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:release-*
    flux.weave.works/ignore: true
...
```

With both of these annotations in place, we'd have log entries that seem to indicate it being both ignored and automated:

```shell
ts=2019-02-18T22:02:34.277718708Z caller=sync.go:66 component=sync-loop resource=default:helmrelease/my-webapi ignore=apply
ts=2019-02-18T22:07:27.170619954Z caller=images.go:33 component=sync-loop error="checking services for new images: helmreleases.flux.weave.works \"my-webapi\" not found"
```

After doing some digging, I think this occurs due to an issue in [pollForNewImages](https://github.com/weaveworks/flux/blob/bd2d3e04a2865b5451fb8ad6cc3671c462705208/daemon/images.go#L33).

It looks like [GetUnlockedAutomatedResources](https://github.com/weaveworks/flux/blob/bd2d3e04a2865b5451fb8ad6cc3671c462705208/daemon/images.go#L109) doesn't take the `policy.Ignore` into account, so the image check fails when comparing with a non-existent flux controller on line 33. Since that error then causes a return, it short circuits image updates for everything else.
