### ISSUE TITLE
Flux fails to clone a repo in one cluster but not in another.

### ISSUE THREAD

**Issue by bricef** [weaveworks/flux#1756]
Flux fails to read a repository. This is strange as flux has been previously configured on a different cluster to use a different folder of the same repository. All repos are under Github.

User reports that trying a different repo also failed to work.

## Original issue
https://weavesupport.zendesk.com/agent/tickets/317

## Log extract

```
ts=2019-02-20T15:55:12.061579015Z caller=loop.go:87 component=sync-loop err="git repo not ready: git clone --mirror: running git command: git [clone --mirror git@github.com:dwightbiddle-ef/ontour-k8s-prod /tmp/flux-gitclone132785868]: context deadline exceeded"
ts=2019-02-20T15:55:14.644257634Z caller=images.go:17 component=sync-loop msg="polling images"
```

**Comment by danbudris** [comment]
We've adjusted the `git-timeout` container argument for the` weave-flux-agent` deployment to 1 minute
```
spec:
      containers:
      - args:
        - --token=$(WEAVE_CLOUD_TOKEN)
        - --connect=wss://cloud.weave.works./api/flux
        - --memcached-hostname=weave-flux-memcached.weave.svc.cluster.local
        - --git-ci-skip=true
        - --git-url=git@github.com:redacted/redacted
        - --git-path=prod
        - --git-branch=master
        - --git-label=redacted
        - --git-timeout=1m
        - --ssh-keygen-dir=/var/fluxd/ssh
```
However, we're still seeing the timeout in the logs:
### Log extract
```
`ts=2019-02-22T16:06:22.409689833Z caller=loop.go:87 component=sync-loop err="git repo not ready: git clone --mirror: running git command: git [clone --mirror git@github.com:redacted/redacted /tmp/flux-gitclone209160108]: context deadline exceeded"
ts=2019-02-22T16:06:24.758439178Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-02-22T16:06:24.758500893Z caller=images.go:27 component=sync-loop msg="no automated services"
```
