### ISSUE TITLE
Ambiguous log error when the chart path is wrong

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#1764]
There is a top level flat to skip dependency updates.  If you change the flag in a repo, it appears that the new value of the flag is ignored.

**Comment by hiddeco** [comment]
Are you implying that `--update-chart-deps=false` does not disable chart updates or that with `--update-chart-deps=true` configurations on `HelmRelease` level are ignored?

**Comment by derrickburns** [comment]
I did not have a flag in my HelmRelease.  I noticed in the logs lines like this:
```
ts=2019-02-26T00:58:43.201735556Z caller=chartsync.go:333 component=chartsync warning="Failed to update chart dependencies" namespace=dev name=api-entry-dev error="stat /tmp/flux-working580982864/charts/api-entry: no such file or directory"
```
Then, I updated my HelmRelease to add the `skipDepUpdate` flag:
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: api-entry-dev
  namespace: dev
spec:
  releaseName: api-entry-dev
  skipDepUpdate: true
  chart:
    git: git@github.com:tidepool-org/dev-ops
    path: charts/api-entry
    ref: master
  values:
    none: none
```
I pushed the change to GitHun.
However, after an hour, I still get the log messages indicating that the dependency file is missing.
