### ISSUE TITLE
values field required in HelmRelease?

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#1773]
If I do not provide a `values` field with at least one value, the Helm operator rejects the HelmRelease.  
```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio-init
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio-init
  chart:
    git: git@github.com:istio/istio
    path: install/kubernetes/helm/istio-init
    ref: master
  values:
    none: none
```
