### ISSUE TITLE
Problem with ACR Helm repo

### ISSUE THREAD

**Issue by timwebster9** [weaveworks/flux#1784]
Following on from #1726 

Got around to trying this again, but it still appears to be broken.

In my `HelmRelease`:
```
spec:
  releaseName: cmc-pdf-service
  chart:
    repository: https://hmcts.azurecr.io/helm/v1/repo
    name: cmc-pdf-service
    version: 0.0.1
    ...
```
In my mounted `repositories.yaml`:
```
  ...
  name: hmcts
  url: https://hmcts.azurecr.io/helm/v1/repo
  ...
```
and then in the flux-helm-operator logs:
```
ts=2019-03-01T17:29:25.640540112Z caller=chartsync.go:343 component=chartsync info="chart download failed" releaseName=cmc-pdf-service resource=software-engineering:helmrelease/cmc-pdf-service err="Failed to fetch https://hmcts.azurecr.io/helm/v1/_blobs/cmc-pdf-service-0.0.1.tgz : 404 Not Found"
```

The correct download URL should be `https://hmcts.azurecr.io/helm/v1/repo/_blobs/cmc-pdf-service-0.0.1.tgz`

Basically `/repo` is being truncated for some reason.

I mentioned this in #1726 and the workaround was to put a trailing `/` on the repo URL in the Helm.

This workaround still works, but you need the `/` on both URLs (in the repositories.yaml and the HelmRelease).  However that now means the documentation is wrong, as it's the only way it works now.
