### ISSUE TITLE
Error upgrading Flux via Helm

### ISSUE THREAD

**Issue by ndarilek** [weaveworks/flux#1813]
Attempting to upgrade Flux from 0.5.1 gives the following error:

```bash
$ helm upgrade flux weaveworks/flux --reuse-values --dry-run
Error: UPGRADE FAILED: render error in "flux/templates/memcached.yaml": template: flux/templates/memcached.yaml:71:9: executing "flux/templates/memcached.yaml" at <eq .Values.memcached...>: error calling eq: invalid type for comparison
```

Running Helm 2.12.3. Not sure if it makes a difference, but I ran an upgrade to Helm 2.13.0 before learning that it wasn't yet supported. `helm init --force-upgrade` may have brought me back to 2.12.3 in that `helm ls` doesn't complain about incompatible client versions, but `helm version` still shows 2.13.0 on the server. Not sure how relevant that is.

Thanks.

**Comment by squaremo** [comment]
Can you show the existing values (i.e., those being summoned with `--reuse-values`)?

**Comment by ndarilek** [comment]
Sure, I think these are them. Gotten via `helm get values flux`:

```yaml
git:
  path: manifests
  url: git@gitlab.com:ndarilek/infrastructure.git
helmOperator:
  create: true
  createCRD: false
```
