### ISSUE TITLE
Git source chart has dependency on chart in incubator repository

### ISSUE THREAD

**Issue by MilanDasek** [weaveworks/flux#1834]
Hi,

I am trying to install this chart,

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-to-cloudwatch
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: prometheus-to-cloudwatch
  chart:
    git: https://github.com/cloudposse/prometheus-to-cloudwatch.git
    ref: master
    path: chart
  values:
    annotations:
        iam.amazonaws.com/role: REDACTED
    env:
      CLOUDWATCH_NAMESPACE: "kubernetes/eks-staging-can"
      CLOUDWATCH_REGION: "eu-west-1"
      CLOUDWATCH_PUBLISH_TIMEOUT: "5"
      PROMETHEUS_SCRAPE_INTERVAL: "20"
      PROMETHEUS_SCRAPE_URL: "http://prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080/metrics"
      CERT_PATH: ""
      KEY_PATH: ""
      ACCEPT_INVALID_CERT: "true"

```

but there is requirements.yaml

```
dependencies:
- name: common
  version: 0.0.4
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
```

I have this error:

`ts=2019-03-15T13:19:00.478662249Z caller=chartsync.go:333 component=chartsync warning="Failed to update chart dependencies" namespace=kube-system name=prometheus-to-cloudwatch error="could not update dependencies in /tmp/flux-working016518383/chart: Error: no repository definition for https://kubernetes-charts-incubator.storage.googleapis.com/. Please add them via 'helm repo add'\n"`

Any idea how to do this?

thx
