### ISSUE TITLE
Adding --sync-garbage-collection flag to deployment throws Error: unknown flag

### ISSUE THREAD

**Issue by gilmoregrills** [weaveworks/flux#1842]
Hi there! 

I just tried updating a cluster with the latest version of flux, which worked fine, but when I added the `--sync-garbage-collection` flag to the deployment we're using the pods fail to start, with the logs returning: 
```
→ kubectl logs flux-6d545bf788-f7nck
Error: unknown flag: --sync-garbage-collection

DESCRIPTION
  fluxd is the agent of flux.

FLAGS
      --connect string                        connect to an upstream service e.g., Weave Cloud, at this base address
      --docker-config string                  path to a docker config to use for image registry credentials
      --git-branch string                     branch of git repo to use for Kubernetes manifests (default "master")
      --git-ci-skip                           append "[ci skip]" to commit messages so that CI will skip builds
      --git-ci-skip-message string            additional text for commit messages, useful for skipping builds in CI. Use this to supply specific text, or set --git-ci-skip
      --git-email string                      email to use as git committer (default "support@weave.works")
      --git-gpg-key-import string             keys at the path given (either a file or a directory) will be imported for use in signing commits
      --git-label string                      label to keep track of sync progress; overrides both --git-sync-tag and --git-notes-ref
      --git-notes-ref string                  ref to use for keeping commit annotations in git notes (default "flux")
      --git-path strings                      relative paths within the git repo to locate Kubernetes manifests
      --git-poll-interval duration            period at which to poll git repo for new commits (default 5m0s)
      --git-set-author                        if set, the author of git commits will reflect the user who initiated the commit and will differ from the git committer.
      --git-signing-key string                if set, commits will be signed with this GPG key
      --git-sync-tag string                   tag to use to mark sync progress for this cluster (default "flux-sync")
      --git-timeout duration                  duration after which git operations time out (default 20s)
      --git-url string                        URL of git repo with Kubernetes manifests; e.g., git@github.com:weaveworks/flux-get-started
      --git-user string                       username to use as git committer (default "Weave Flux")
      --k8s-namespace-whitelist strings       experimental, optional: restrict the view of the cluster to the namespaces listed. All namespaces are included if this is not set.
      --k8s-secret-data-key string            data key holding the private SSH key within the k8s secret (default "identity")
      --k8s-secret-name string                name of the k8s secret used to store the private SSH key (default "flux-git-deploy")
      --k8s-secret-volume-mount-path string   mount location of the k8s secret storing the private SSH key (default "/etc/fluxd/ssh")
      --kubernetes-kubectl string             optional, explicit path to kubectl tool
  -l, --listen string                         listen address where /metrics and API will be served (default ":3030")
      --listen-metrics string                 listen address for /metrics endpoint
      --memcached-hostname string             hostname for memcached service. (default "memcached")
      --memcached-service string              SRV service used to discover memcache servers. (default "memcached")
      --memcached-timeout duration            maximum time to wait before giving up on memcached requests. (default 1s)
      --registry-burst int                    maximum number of warmer connections to remote and memcache (default 10)
      --registry-ecr-exclude-id strings       do not scan ECR for images in these AWS account IDs; the default is to exclude the EKS system account (default [602401143452])
      --registry-ecr-include-id strings       restrict ECR scanning to these AWS account IDs; if empty, all account IDs that aren't excluded may be scanned
      --registry-ecr-region strings           restrict ECR scanning to these AWS regions; if empty, only the cluster's region will be scanned
      --registry-exclude-image strings        do not scan images that match these glob expressions; the default is to exclude the 'k8s.gcr.io/*' images (default [k8s.gcr.io/*])
      --registry-insecure-host strings        let these registry hosts skip TLS host verification and fall back to using HTTP instead of HTTPS; this allows man-in-the-middle attacks, so use with extreme caution
      --registry-poll-interval duration       period at which to check for updated images (default 5m0s)
      --registry-rps float                    maximum registry requests per second per host (default 50)
      --registry-trace                        output trace of image registry requests to log
      --ssh-keygen-bits uint                  -b argument to ssh-keygen (default unspecified)
      --ssh-keygen-dir string                 directory, ideally on a tmpfs volume, in which to generate new SSH keys when necessary
      --ssh-keygen-type string                -t argument to ssh-keygen (default unspecified)
      --sync-garbage-collection               experimental; delete resources that were created by fluxd, but are no longer in the git repo
      --sync-interval duration                apply config in git to cluster at least this often, even if there are no new commits (default 5m0s)
      --token string                          authentication token for upstream service
      --version                               get version number
```
I included the full error text because the flag it says is unknown is right there in the list of flags 😭 

The deployment I'm using looks like this: 
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io.port: "3031" # tell prometheus to scrape /metrics endpoint's port.
      labels:
        name: flux
    spec:
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400 # when mounted read-only, we won't be able to chmod

      # This is a tmpfs used for generating SSH keys. In K8s >= 1.10,
      # mounted secrets are read-only, so we need a separate volume we
      # can write to.
      - name: git-keygen
        emptyDir:
          medium: Memory

      containers:
      - name: flux
        # Release or image version at https://quay.io/weaveworks/flux
        # and replace the tag here.
        image: quay.io/weaveworks/flux:1.11.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 3030 # informational
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh # to match location given in image's /etc/ssh/config
          readOnly: true # this will be the case perforce in K8s >=1.10
        - name: git-keygen
          mountPath: /var/fluxd/keygen # to match location given in image's /etc/ssh/config

        args:

        # if you deployed memcached in a different namespace to flux,
        # or with a different service name, you can supply these
        # following two arguments to tell fluxd how to connect to it.
        # - --memcached-hostname=memcached.default.svc.cluster.local
        # - --memcached-service=memcached
        - --memcached-timeout=100ms

        # this must be supplied, and be in the tmpfs (emptyDir)
        # mounted above, for K8s >= 1.10
        - --ssh-keygen-dir=/var/fluxd/keygen

        # replace or remove the following URL
        - --git-url=git@github.com:ourorg/repo.git
        - --git-branch=master
        - --git-path=system-test
        - --git-poll-interval=120s
        - --registry-poll-interval=120s
        - --sync-garbage-collection‌
        # uncomment this to exclude images from scanning
        # - --registry-exclude-image
        # include these next two to connect to an "upstream" service
        # (e.g., Weave Cloud). The token is particular to the service.
        # - --connect=wss://cloud.weave.works/api/flux
        # - --token=abc123abc123abc123abc123

        # serve /metrics endpoint at different port.
        # make sure to set prometheus' annotation to scrape the port value.
        - --listen-metrics=:3031

        # list of valid namespaces to export, empty for all namespaces.
        # comma separated list of namespaces to monitor for workloads.
        - --k8s-namespace-whitelist=kube-system
```

Is there something I'm missing? An additional flag needed to use new/experimental features? 

Thanks in advance ❤️
