### ISSUE TITLE
Helm operator fails to upgrade due to existing release

### ISSUE THREAD

**Issue by pmquang** [weaveworks/flux#1854]
Hi, 

I have a Helm Release look like  ( and it installed successfully before ) : 

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "false"
    #flux.weave.works/tag.chart-image: glob:stg-*
  name: profile-v2-api
  namespace: dev
spec:
  chart:
    git: git@bitbucket.org:xxx/flux.git
    path: charts/common-service
    ref: master  
  releaseName: profile-v2-api
```

After upgrading K8S cluster ( GKE ), I have some error log like:

```ts=2019-03-22T04:12:40.446368403Z caller=release.go:186 component=release error="Chart release failed: profile-v2-api: &status.statusError{Code:2, Message:\"a release named profile-v2-api already exists.\\nRun: helm ls --all profile-v2-api; to check the status of the release\\nOr run: helm del --purge profile-v2-api; to delete it\", Details:[]*any.Any(nil)}"```

Why this error happened ? How to manually mark this release belong to the Helm Operator ( to make this error gone ) ? 

How Helm Operator recognize which releases it release or not ? ( it get some information in memcached ) ? 

Regards
