### ISSUE TITLE
flux getting resource not found for API error when the resource kind is a [resource]List

### ISSUE THREAD

**Issue by winstonliu1111** [weaveworks/flux#1860]
I have a manifest like the following, which is a List of the Role resource

  ```yaml
  ---
  # Source: prometheus-operator/templates/prometheus/role-specificNamespace.yaml
  
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleList
  items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: prom-op-prometheus-operato-prometheus
      labels:
        app: prometheus-operator-prometheus
  
        chart: prometheus-operator-1.7.0
        release: "prom-op"
        heritage: "Tiller"
        flux.weave.works/stack: prom-op
  
      namespace: "kube-system"
    rules:
    - apiGroups:
      - ""
      resources:
      - nodes
      - services
      - endpoints
      - pods
      verbs:
      - get
      - list
      - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: prom-op-prometheus-operato-prometheus
      labels:
        app: prometheus-operator-prometheus
  
        chart: prometheus-operator-1.7.0
        release: "prom-op"
        heritage: "Tiller"
        flux.weave.works/stack: prom-op
  
      namespace: "isg-system"
    rules:
    - apiGroups:
      - ""
      resources:
      - nodes
      - services
      - endpoints
      - pods
      verbs:
      - get
      - list
      - watch
  ```

if I do kubectl apply -f of the above manifest, the roles are created.

but if i tried to check this into a git repo that flux is linked to, I get the following error in the logs of the flux pod:

  ```
  ts=2019-03-25T18:11:21.151294067Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: resource not found for API rbac.authorization.k8s.io/v1, kind RoleList"
  ```

if I inspect the api-resources, I see the following.
  ```bash
  $ kubectl api-resources -o wide |grep Role
  clusterrolebindings                                rbac.authorization.k8s.io            false        ClusterRoleBinding               [create delete deletecollection get list patch update watch]
  clusterroles                                       rbac.authorization.k8s.io            false        ClusterRole                      [create delete deletecollection get list patch update watch]
  rolebindings                                       rbac.authorization.k8s.io            true         RoleBinding                      [create delete deletecollection get list patch update watch]
  roles                                              rbac.authorization.k8s.io            true         Role                             [create delete deletecollection get list patch update watch]
  ```

I see similar errors for other manifests when resource kind is RoleBindingList or ConfigMapList as well.

Is this expected?  I'm using the quay.io/weaveworks/flux:1.11.0 image.
