### ISSUE TITLE
Debug helmrelease before committing to GitOps

### ISSUE THREAD

**Issue by michaelfig** [weaveworks/flux#1864]
Feature request: Add a command to `fluxctl` that can debug  a helmrelease yaml without having to apply it to the cluster and ensure all the chart references are pushed.

Say I have a `myrelease.yaml` file:
```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: my-release-name
  chart:
    git: somewhere:/foo/bar.git
    ref: master
    path: charts/myserver
  values:
    image:
      repository: my-image-repo/my-imagebamappserver
      tag: foobar
    replicaCount: 2
    ingress:
      enabled: true
[...]
```

I'd like something like `fluxctl helm-template ./myrelease.yaml /path/to/my/chart` to run the moral equivalent of:

```
helm template --values=- --namespace=dev --name=my-release-name /path/to/my/chart
```

where the stdin (used by the `--values=-` switch), is generated like:
```yaml
image:
  repository: my-image-repo/my-image
  tag: foobar
replicaCount: 2
ingress:
  enabled: true
[...]
```

This would make debugging flux helmreleases a lot more pleasant!

If you are willing to take a PR to implement this (or a modified proposal), let me know, and I can try to cook one up.

Thanks,
Michael.
