### ISSUE TITLE
invalid service ID when applying resources (cluster-roles)

### ISSUE THREAD

**Issue by davidkarlsen** [weaveworks/flux#1934]
I get:

```
devops/flux-devops-6df4b747d7-b444g[flux]: ts=2019-04-14T14:19:20.675738823Z caller=loop.go:412 component=sync-loop err="executing HTTP request: 400 Bad Request parsing <cluster>:clusterrole/sealed-secrets-icp-admin-aggregate: invalid service ID\n"
````

when applying:
```
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-icp-admin-aggregate
  labels:
    rbac.icp.com/aggregate-to-icp-admin: "true"
rules:
- apiGroups:
  - "bitnami.com"
  resources:
  - sealedsecret
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
...
```

running weaveworks/flux:1.12.0

I can kubectl replace -f <theroles> just fine

Seems related: https://github.com/weaveworks/flux/pull/1282
