### ISSUE TITLE
No automatic roll-outs when HelmRelease has multiple images

### ISSUE THREAD

**Issue by dvelitchkov** [weaveworks/flux#1961]
We have a `HelmRelease` CRD that specifies multiple images, like so:

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  labels:
    app: suricata
  name: suricata
  namespace: staging
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.suricata_image: glob:staging*
    flux.weave.works/tag.service_image: glob:staging*
    flux.weave.works/tag.nginx_image: glob:staging*

spec:
  values:
    suricata_image:
      repository: <redacted>/suricata-service-suricata:staging-v0.1.0-rc02
    service_image:
      repository: <redacted>/suricata-service-service:staging-v0.1.0-rc02
    nginx_image:
      repository: <redacted>/suricata-service-nginx:staging-v0.1.0-rc02
```

And values.yaml has the images listed top-level:
```yaml
nginx_image:
  repository: <redacted>:staging-v0.1.0-rc02
  pullPolicy: IfNotPresent
  volumeMounts: ...snip...

suricata_image:
  repository: <redacted>:staging-v0.1.0-rc02
  pullPolicy: IfNotPresent
  volumeMounts:...snip....

service_image:
  repository: <redacted>:staging-v0.1.0-rc02
  pullPolicy: Always
  volumeMounts:...snip...
```

Pushing new images to our docker repo, however, doesn't trigger any automated deployments. The Helm chart itself is fine, Flux runs it, the k8s resources are created, everything is fine. Except no autoreleases are happening. No errors in the logs. 

Fluxctl doesn't show any images for this controller. 

After reading some (somewhat contradictory) docs in various places, we tried making one of the image annotations be `chart-image`, and `fluxctl list-images` does show one of the 3 images, but only one. 

Seems like a bug? 

Is `chart-image` mandatory? Seems like it is? Seems like you must have it for Flux to process this at all, but if you have it - only one of your images "counts"? 

Without `chart-image`, it seems like flux doesn't process the `HelmRelease` CRD at all?

**Comment by dvelitchkov** [comment]
Ok, sorry, I must be tired. I read https://github.com/weaveworks/flux/blob/322cdc2397524e7ca65850bff724d0ecda532fd4/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux multiple times and *still* managed to get it wrong. 

For future ref, needs to be:
```yaml
    service_image:
         image:
            repository: ....
            tag:....
```
instead of
```yaml
     service_image:
            repository: ....
            tag:....
```
