### ISSUE TITLE
Chart has diverged due to manual Chart release

### ISSUE THREAD

**Issue by MilanDasek** [weaveworks/flux#1999]
Hi,

we have repo in bitbucket. We are using 2 branches - master and production. We have 2 EKS clusters - staging (master repo) and production (repo same name)

We notice strange thing, sometimes, when we update master - especially image version in charts in master, we do see that this change is propagated to production EKS despite there wasn't any action in git.

I see this in flux operator log:
```
ts=2019-04-30T13:01:37.229176439Z caller=chartsync.go:580 component=chartsync error="Release bootstrap-service: Chart has diverged due to manual Chart release"
ts=2019-04-30T13:01:37.229417761Z caller=release.go:149 component=release info="processing release bootstrap-service (as bootstrap-service)" action=UPDATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-04-30T13:01:38.036376571Z caller=release.go:149 component=release info="processing release export-service (as cec55100-6b0c-11e9-866e-0226e32efd9c)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=300s
```

Our Flux is configured:
```
git:
  # URL of git repo with Kubernetes manifests; e.g. git.url=ssh://git@github.com/weaveworks/flux-get-started
  url: "git@bitbucket.org:clevermaps/REDACTEDgitops.git"
  # Branch of git repo to use for Kubernetes manifests
  branch: "production"
  # Path within git repo to locate Kubernetes manifests (relative path)
  path: "common,eks-production"
```

What could be wrong?

Thank you

**Comment by MilanDasek** [comment]
docker.io/weaveworks/flux:1.12.0
docker.io/weaveworks/helm-operator:0.8.0

**Comment by squaremo** [comment]
@MilanDasek How do you refer to charts in HelmRelease resources -- are they in git, or from a Helm repository? When you say "update master", do you mean changes to HelmRelease manifests, or to charts?

**Comment by MilanDasek** [comment]
Oh, I know where is the problem

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: XXX
  namespace: YYY
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "false"
spec:
  releaseName: XXX
  chart:
    git: git@bitbucket.org:ZZZ/can-docker-gitops.git
    path: common/charts/XXX
    ref: **master**
  values:
```

so I need to change reference to "production" branch, am I right?

Thanks!
