### ISSUE TITLE
incorrect workload names in flux

### ISSUE THREAD

**Issue by jan-schumacher** [weaveworks/flux#2011]
After some researches and testing I figured out that all helm releases are named the same in flux and I can’t figure out why.
```
default:helmrelease/redis                     application
default:helmrelease/redis                     application
default:helmrelease/redis                     application
default:helmrelease/redis                     application
default:helmrelease/redis                     application
default:helmrelease/redis                     application
default:helmrelease/redis                     chart-image
```
the container `application` is obvious, because all image keys are under application key. Thats correct.
But depending on what deploys last the workload is named `default:helmrelease/redis`. When I delete redis the workload is `default:helmrelease/fluxcloud`.

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: some-app
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: some-app
  chart:
    git: git@1.2.3.4:/repository/repo.git
    path: charts/some-chart
    ref: master
  values:
    application:
      image: eu.gcr.io/project-name/some-app:master-123
    other:
      settings: {}
```

This is how a typical helm release looks like in our case. Any ideas what is wrong or did I find a bug in flux? (edited) 

**Setup: **
Kubernetes 1.12.7-gke.10
Helm v2.12.2
flux 1.12.1
fluxctl 1.12.0
flux-helm-operator 0.8.0

**Reproduce:**
1. create 2 helmReleases
1.1. Call one faulty the other faulty2
1.2. Add them to the repository
1.3. Do `$ fluxctl sync`
2. Do `$ fluxctl list-workloads | grep helmrelease`

**Error**
The output of `$ fluxctl list-workloads | grep helmrelease`
```
default:helmrelease/faulty2                                                                          
default:helmrelease/faulty2
```

**Expected behavior**
The workload names should match the release names. `$ fluxctl list-workloads | grep helmrelease` should produce something like
```
default:helmrelease/faulty                                                                         
default:helmrelease/faulty2
```
