### ISSUE TITLE
helm operator does not update chart repositories index

### ISSUE THREAD

**Issue by jan-schumacher** [weaveworks/flux#2059]
We had problems using some charts from default stable chart repository. They were just not available in the cached index of the `flux-helm-operator`. 
Our cluster is running since February 2019 and we had updated the `flux-helm-operator` several times but the index of helm chart repositories just didn't showed up the needed charts. 
After updating the index manually `kubectl exec -it flux-helm-operator helm repo update` it worked directly without any problems.

Unfortunately I have no logs of the process because I was fiddling around quiet a lot.

**Comment by hiddeco** [comment]
Tried to replicate this but came to the conclusion I need some more information.

1. Are you using charts from the stable repository using a chart source or via git?
2. In case of the former, it does not use the cached index but instead just downloads the tarball using the index file exposed by the chart repository, the tarball should already include all dependencies (making it very unlikely you are fetching them from the chart repository).
3. In case of the latter, if you are running the Helm operator with the default settings, it should try to update all dependencies on each run, this [should also run `helm repo update`](https://github.com/weaveworks/flux/blob/dd1b20718d82f445557b41ac8261c78aad159ecb/integrations/helm/chartsync/deps.go#L54). Do you by any chance have `SkipDepUpdate` set to `true` in your `HelmRelease`, or `--update-chart-deps` set to `false`?

I think all of the above can be answered by sharing a minimal `HelmRelease` that resulted in the described error.

**Comment by jan-schumacher** [comment]
> Tried to replicate this but came to the conclusion I need some more information.
> 
> 1. Are you using charts from the stable repository using a chart source or via git?
I used in the first place the git repo but switched to the chart repository after you told me it is possible

> 2. In case of the former, it does not use the cached index but instead just downloads the tarball using the index file exposed by the chart repository, the tarball should already include all dependencies (making it very unlikely you are fetching them from the chart repository).
> 3. In case of the latter, if you are running the Helm operator with the default settings, it should try to update all dependencies on each run, this [should also run `helm repo update`](https://github.com/weaveworks/flux/blob/dd1b20718d82f445557b41ac8261c78aad159ecb/integrations/helm/chartsync/deps.go#L54). Do you by any chance have `SkipDepUpdate` set to `true` in your `HelmRelease`, or `--update-chart-deps` set to `false`?

this is our flux helm release setup:
```
image:
  repository: docker.io/weaveworks/flux
  tag: 1.12.2

helmOperator:
  create: true
  createCRD: false
  configureRepositories:
    enable: true
    repositories:
      - cache: stable-index.yaml
        name: stable
        url: https://kubernetes-charts.storage.googleapis.com
      - name: bitnami
        url: https://charts.bitnami.com
        cache: bitnami-index.yaml
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 300Mi

git:
  # URL of git repo with Kubernetes manifests; e.g. git.url=ssh://git@github.com/weaveworks/flux-get-started
  url: "git@10.110.127.252:/repository/k8s-cluster-helm-charts.git"
  # Branch of git repo to use for Kubernetes manifests
  branch: "master"
  # Path within git repo to locate Kubernetes manifests (relative path)
  path: ""
  # Username to use as git committer
  user: "git"
  # Email to use as git committer
  email: "flux@24technology.de"
  # If set, the author of git commits will reflect the user who initiated the commit and will differ from the git committer.
  setAuthor: false
  # Label to keep track of sync progress
  label:
  # Append "[ci skip]" to commit messages so that CI will skip builds
  ciSkip: false
  # Period at which to poll git repo for new commits
  pollInterval: "5m"
  # Duration after which git operations time out
  timeout: "20s"
  # generate a SSH key named identity: ssh-keygen -q -N "" -f ./identity
  # create a Kubernetes secret: kubectl -n flux create secret generic flux-ssh --from-file=./identity
  # delete the private key: rm ./identity
  # add ./identity.pub as a read-only deployment key in your GitHub repo where the charts are
  # set the secret name (flux-ssh) below
  secretName: "tudilu"


ssh:
  known_hosts: "some host certs"

prometheus:
  enabled: false

additionalArgs:
 - --connect=ws://fluxcloud-service
```

> 
> I think all of the above can be answered by sharing a minimal `HelmRelease` that resulted in the described error.

**Comment by hiddeco** [comment]
Do you also have a copy of one of the `HelmRelease`s that fail?

**Comment by jan-schumacher** [comment]
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis-ha
  namespace: msis
  annotations:
    flux.weave.works/automated: "false"
#    flux.weave.works/tag.chart-image: semver:4.0.14
spec:
  releaseName: redis-ha
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: redis-ha
    version: 3.4.2
  values:
    image:
      registry: docker.io
      repository: redis
      tag: 5.0.3-alpine
    redis:
      masterGroupName: msis
    rbac:
      create: false
```

**Comment by hiddeco** [comment]
Created a Helm release with the given `values.yaml` and installed the `HelmRelease` without any problems (except for failed scheduling due to anti-affinity rules and running minikube).

Tried to install the following `HelmRelease` with a chart from the Bitnami repository to see if I had to run `helm repo update`, I did not (which was expected as we get the tarball [by fetching it directly](https://github.com/weaveworks/flux/blob/1.12.2/integrations/helm/chartsync/download.go#L72-L98) from the repository).

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: memcached
spec:
  releaseName: memcached
  chart:
    repository: https://charts.bitnami.com
    name: memcached
    version: 1.5.7

```
