### ISSUE TITLE
Doesn't update & trigger deployment of HelmRelease

### ISSUE THREAD

**Issue by dminca** [weaveworks/flux#2067]
**Describe the bug**
_Regression bug:_ Flux is not able to match the RegEx pattern of the `HelmRelease` image label, thus not triggering the update (in git repo) & deployment of the `HelmRelease`.

**To Reproduce**
Steps to reproduce the behaviour:
0. Given a Helm Chart with the following `values.yaml` file:
```yaml
<snip>
image:
  repository: marcel-registry.com/myapp
  tag: master-231kdsj92
<snip>
```

1. Create a `HelmRelease` with the following values
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace: myapp-ns
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: myapp
  chart:
    git: ssh://git@marcel-repo.com/myapp.git
    path: helm/myapp
    ref: master
  values:
    image:
      registry: marcel-registry.com/myapp
      tag: master-3d30e14fd7
```
2. Update & Release of `HelmRelease` actions not firing
3. No errors reported in the logs (expecting `RegEx pattern mismatch` thrown)

**Expected behavior**
Flux detected a new image in the registry and triggered an update of the image label (in git repo) and triggered a deployment of the `HelmRelease`

**Logs**

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: `1.12.2`
- Helm Operator version: `0.9.2`
- Kubernetes version: `v1.11.7`
- Git provider: `Atlassian Bitbucket`
- Container registry provider: `AWS ECR`
