### ISSUE TITLE
Wrong indentation is flux deployment template

### ISSUE THREAD

**Issue by rkouyoumjian** [weaveworks/flux#2099]
The indentation is 8 instead of 6 for Values.extraVolumes
 https://github.com/weaveworks/flux/blob/master/chart/flux/templates/deployment.yaml#L85

**To Reproduce**
Steps to reproduce the behaviour:
1. Create values.yaml with the following content:
```yaml
extraVolumes:
- name: ca-cert
  hostPath:
    path: /shared/ca-certificates.crt
```
2. Running helm with dry-run 
3. the added volume is not correctly indented.
```yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: flux
  template:
    metadata:
      annotations:
      labels:
        app: flux
        release: flux
    spec:
      serviceAccountName: flux
      volumes:
      - name: kubedir
        configMap:
          name: flux-kube-config
      - name: sshdir
        configMap:
          name: flux-ssh-config
          defaultMode: 0600
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
        - name: ca-cert
          hostPath:
            path: /shared/ca-certificates.crt
```
**Expected behavior**
Correct indentation
```yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: flux
  template:
    metadata:
      annotations:
      labels:
        app: flux
        release: flux
    spec:
      serviceAccountName: flux
      volumes:
      - name: kubedir
        configMap:
          name: flux-kube-config
      - name: sshdir
        configMap:
          name: flux-ssh-config
          defaultMode: 0600
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      - name: ca-cert
        hostPath:
          path: /shared/ca-certificates.crt

Trying to run the helm will result in:
Error: YAML parse error on flux/templates/deployment.yaml: error converting YAML to JSON: yaml: line 38: did not find expected key
