### ISSUE TITLE
Getting empty values when using  valueFileSecrets

### ISSUE THREAD

**Issue by vovkanaz** [weaveworks/flux#2124]
**Describe the bug**
Always getting empty value when using valueFileSecrets

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup? ----> We a trying to setup Helmrelease:

```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata: 
  annotations: 
    flux.weave.works/automated: "false"
  ...
  ...
  values: 
    valueFileSecrets:
        - name: "alert-config"
```

alert-config is a sealed-secret config file according to https://github.com/bitnami-labs/sealed-secrets 
---------
the sealedsecret file begins, if decode it:

```
alertmanagerConfigFile:
  global:
    resolve_timeout: 5m
  route:
```
----------

in helmchart we have a secret:
```
kind: Secret
apiVersion: v1
data:
  alertmanager.yaml: {{ default "default" .Values.alertmanagerConfigFile }}
```

**Expected behaviour**
base64 config passed to the secret
```
kind: Secret
apiVersion: v1
data:
  alertmanager.yaml: base64hash
```

**Logs**
We've had always empty_values  passed to the secret
```
kind: Secret
apiVersion: v1
data:
  alertmanager.yaml: empty_value
```

**Comment by hiddeco** [comment]
Is the data in your `SealedSecret` file listed under a `values.yaml` key? E.g. (decrypted) version:

```
apiVersion: v1
kind: Secret
metadata:
  name: alert-config
data:
  values.yaml: <base64 encoded version of alertManagerConfigFile>
```
