### ISSUE TITLE
Keeping HelmReleases DRY

### ISSUE THREAD

**Issue by michaelgeorgeattard** [weaveworks/flux#2131]
We are using multiple HelmReleases to handle application versioning:

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: common-v1-test
  namespace: test
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:^1.0
spec:
  releaseName: common-v1-test
  chart:
    repository: http://chartmuseum-chartmuseum.management:8080
    name: bar
    version: 0.7.6
  values:
    apiVersion: v1
    image:
      repository: 123.dkr.ecr.eu-west-1.amazonaws.com/common
      tag: 1.8.2
    dashboard:
      enabled: true
    secret:
      create: false
```

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: common-v2-test
  namespace: test
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:^2.0
spec:
  releaseName: common-v2-test
  chart:
    repository: http://chartmuseum-chartmuseum.management:8080
    name: bar
    version: 0.7.6
  values:
    apiVersion: v2
    image:
      repository: 123.dkr.ecr.eu-west-1.amazonaws.com/common
      tag: 2.0.2
    dashboard:
      enabled: true
    secret:
      create: false
```

* Is it currently possible to avoid code duplication (keeping code DRY)?
* If not, are there any plans for such functionality, using inheritance/golang templates/otherwise?
