### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#2137]
**Describe the bug**
```
ts=2019-06-07T17:59:27.707447931Z caller=release.go:479 component=release err="Object 'Kind' is missing in 'null'"
```

**To Reproduce**
Provide a helm installation with an empty manifest file.  This is natural when the helm file has flags for turning an entire manifest on or off. For example, in file `foo.yaml`:
```
{{ if .Values.useHttps }}
manifest
{{ end }}
```
**Expected behavior**
This is not really an error.  In any case, use the file name if possible in the error message:

```
"Object 'Kind' is missing in 'foo.yaml'"
```

**Comment by hiddeco** [comment]
I tried to install the [mariadb chart](https://github.com/helm/charts/tree/master/stable/mariadb) with the following `HelmRelease`:

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mariadb
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mariadb
    version: 6.4.2
  values:
    existingSecret: existing
```

With `existingSecret` set, [this should replicate the issue you are describing](https://github.com/helm/charts/blob/master/stable/mariadb/templates/secrets.yaml#L1), I do however not see the reported error in the logs:

```
ts=2019-06-11T08:51:47.484130905Z caller=operator.go:296 component=operator info="enqueuing release" resource=default:helmrelease/mariadb
ts=2019-06-11T08:51:50.698949625Z caller=release.go:167 component=release info="processing release default-mariadb (as default-mariadb)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-06-11T08:53:17.088458837Z caller=operator.go:296 component=operator info="enqueuing release" resource=default:helmrelease/xxx
```
