### ISSUE TITLE
Add another values structure

### ISSUE THREAD

**Issue by RGPosadas** [weaveworks/flux#2144]
Currently, Flux can interpret these common `values` formatting in order to automate images:

```
values:
  image: repo/image:version
```

```
values:
  image: repo/image
  tag: version
```

```
values:
  image:
    repository: repo/image
    tag: version
```

It would be nice for Flux to be able to understand this structure as well:
```
values:
  image:
    registry: repo
    repository: image
    tag: version
```
