### ISSUE TITLE
Order of HelmRelease apply in each sync

### ISSUE THREAD

**Issue by ysaakpr** [weaveworks/flux#2170]
**Describe the feature**
I would like to know if there is any specific order the HelmRelease are applied during a sync operation. Because in my release repo there are 100s of HelmRelease files which are managed via CI/CD pipelines. So if there are changes happened, I would like to keep the helm release to apply the changes in a controlled order, just because of the dependency that One HelmRelease has on another.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ambassador
  namespace: dev
spec:
  order: 12345(default 1000)
  chart:
    name: ambassador
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 2.8.2
```

Feel free to add a diagram if that helps explain things.

**Expected behaviour**
This way we can ensure that some of the helm releases is done at first and some are done at last, and dependency can be managed
