### ISSUE TITLE
Should allow URL schema in auth configs, like dockerconfig does.

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#453]
This results in auth error:
```YAML
registry:
  auths:
    "https://gcr.io":
      auth: "..."
```
...but this works:
```YAML
registry:
  auths:
    "gcr.io":
      auth: "..."
```
