### ISSUE TITLE
Handle unversioned images in deployments/rcs

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#92]
It's possible that an image used in a pod template doesn't have a version/tag, e.g.,

```
    spec:
      containers:
      - name: fluxy
        image: weaveworks/fluxy
```

We should be able to handle this. One way would be to return an error and make the user force the operation (assuming we had that force option). Another would be to just replace it with a versioned image, silently or otherwise.

Coming from the other direction, it'd be good to let people supply an unversioned image name to `fluxctl release`, to mean "use the latest".
