### ISSUE TITLE
Helm upgrades stop working when multiple CRs target the same chart/namespace

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/flux#950]
Steps to reproduce:

Create a repo and place the [podinfo](https://github.com/stefanprodan/k8s-podinfo/tree/master/chart/stable/podinfo) chart inside a `charts` dir.

Create the frontend CR in the `config` dir:

```yaml
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: frontend
  namespace: default
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  values:
    - name: image.repository
      value: stefanprodan/podinfo
    - name: image.tag
      value: 0.0.6
```

Create the backend CR:

```yaml
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: backend
  namespace: default
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  releaseName: backend
  values:
    - name: image.repository
      value: stefanprodan/podinfo
    - name: image.tag
      value: 0.0.6
```

Commit the CRs and wait till they get installed.

Change the backend version to `0.0.7` and commit the changes.

Check if the CR has been updated with:

```
kubectl get fluxhelmreleases backend -o yaml

....
  values:
  - name: image.repository
    value: stefanprodan/podinfo
  - name: image.tag
    value: 0.0.7
```

Check if the deployment is still on the `0.0.6` tag:

```
kubectl describe deployment backend-podinfo

...
  Containers:
   podinfo:
    Image:  stefanprodan/podinfo:0.0.6
    Port:   9898/TCP
```
