### ISSUE TITLE
Change Custom Resource values data structure

### ISSUE THREAD

**Issue by tamarakaufler** [weaveworks/flux#951]
**Problem**

The current implementation of FluxHelmRelease Custom Resources uses the following format for providing customizations:

```
values:
  - name: imageTag
    value: a00000a
  - name: memory
    value: 4Gi
``` 

This implementation can be simplified.

**A/C**

The user can add his customizations in the Custom Resource for a chart release in the form:

```
values:
  imageTag: a00000a
  memory: 4Gi
```
