### ISSUE TITLE
ignored is ignored, sometimes.

### ISSUE THREAD

**Issue by bboreham** [weaveworks/flux#954]
Given a config in git starting as follows:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
```

I `kubectl apply` a Deployment config like this:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/ignored: "true"
```

a minute or two later it is back the way it was before, only with `deployment.kubernetes.io/revision` and `observedGeneration` two higher than before.

After one or two retries my new config will stick.
