### ISSUE TITLE
Helm Operator Doesn't Accept Variables

### ISSUE THREAD

**Issue by rossedman** [weaveworks/flux#982]
It appears the Helm Operator does not accept variables properly, it also does not accept boolean values as shown in the documentation. Here is an example of my release file, maybe I am misunderstanding something. I have double checked the variable paths multiple times for my chart, any advice on this? Thanks.

```
---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: ingress
  namespace: ingress
  labels:
    chart: ingress
spec:
  chartGitPath: ingress
  values:
  - name: nginx-ingress.controller.daemonset.useHostPorts
    value: "true"
  - name: nginx-ingress.controller.nodeSelector.pool_type
    value: lbe
  - name: nginx-ingress.controller.service.type
    value: ClusterIP
  - name: nginx-ingress.controller.stats.enabled
    value: "true"
  - name: nginx-ingress.controller.extraArgs.default-ssl-certificate
    value: nginx-ingress/default-ssl-certificate
```

**Comment by rossedman** [comment]
@tamarakaufler Would be interested to see how this is resolved. This is a pretty big blocked. Can provide more insights if needed but have not found a single variable that works yet. Is it better to take the approach [Bitnami did for this piece](https://github.com/bitnami-labs/helm-crd/blob/master/examples/mariadb.yaml#L10)? Is there a reason they are declared individually?

**Comment by tamarakaufler** [comment]
I suggest using _controller.daemonset.useHostPorts_ rather than _nginx-ingress.controller.daemonset.useHostPorts_, as there is:

```
controller:
....
  daemonset:
    useHostPort: false

in the nginx-ingress values.yaml file.
```

Also one thing I have come across is that some properties cannot not be overriden after the initial setup/deployment of the application.

I tested this successfully in the past, will retest again.

Please let me know how you get on.

**Comment by rossedman** [comment]
@tamarakaufler The chart I am using has a dependency on the nginx-ingress controller chart. So it has to be prefaced with `nginx-ingress` as that's how it looks in my values.yml

Here is example of my values.yml

```
nginx-ingress:
  controller:
    kind: DaemonSet
    service:
      type: LoadBalancer
  defaultBackend:
    image:
      repository: gcr.io/google_containers/defaultbackend
      tag: "1.4"
  rbac:
    create: true
```

With this structure, would it still make sense to remove `nginx-ingress` prefix? 

Thanks for response.

**Comment by rossedman** [comment]
Here is a more simple example that did not work for me:

Release file:
```
---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: filebeats
  namespace: logging
  labels:
    chart: filebeats
spec:
  chartGitPath: filebeats
  values:
    - name: config.index.name
      value: dev-test
    - name: config.index.pattern
      value: dev-test-*
```

default values.yml in chart
```
config:
  elastic:
    host: REDACTED
    port: "443"

  index:
    name: dev
    pattern: dev-*

image:
  repository: docker.elastic.co/beats/filebeat
  tag: 6.2.2

tolerations:
  - operator: "Exists"
```

**Comment by tamarakaufler** [comment]
@rossedman 
With the values.yaml setup you have, the nginx-ingress prefix of course makes sense. I was looking at the official nginx-ingress chart.

**Comment by tamarakaufler** [comment]
@rossedman
Are you saying that none of the parameter overriding works for you? I tested various scenarios and they worked for me. There may be cases I missed, which will be investigated.

**Comment by tamarakaufler** [comment]
If some overriding works for you it would be helpful if you could specify which of the overriding does NOT work, ie parameter name and value (the way it is in your FluxHelmRelease custom resource and in the values.yaml file).

**Comment by rossedman** [comment]
@tamarakaufler I have not been able to have any over riding work. I can run the charts manually or with value files and they work, it does not work with the CRD. I will try the example files. I also updated to the new helm-operator:alpha and am running flux:1.2.3 I think. Do I need to run an alpha of flux?

Thanks!

**Comment by tamarakaufler** [comment]
Intriguing. 
You have a correct flux version. There is no flux alpha.

**Comment by rossedman** [comment]
@tamarakaufler last i checked the operator fails when using booleans as well. everything must be a string.

**Comment by tamarakaufler** [comment]
yes, booleans must be provided as strings

**Comment by tamarakaufler** [comment]
Confirmed that:

- variables with simple, one level, names (image, imageTag etc) work
- variables with dotted names (eg resources.requests.memory do not work)

**Comment by tamarakaufler** [comment]
The cause is known now, implementation of the fix has started.

**Comment by rossedman** [comment]
@tamarakaufler great! tag me on the pr so I can see how it was solved. i'm interested in seeing that fix.

**Comment by tamarakaufler** [comment]
@rossedman Definitely. Will do.

**Comment by tamarakaufler** [comment]
A new image with the fix pushed (quay.io/weaveworks/helm-operator:alpha)

@rossedman No PR created as yet as I need to write tests first. However, the implementation can be seen in: 
         https://github.com/weaveworks/flux/compare/982-overriding-variables-issue

Please let me know how it works for you and any issues you encounter. Thank you.

**Comment by tamarakaufler** [comment]
@rossedman I looked again at your example above. Looking at the values.yaml file I realised I still need to fix the override for the following parameter input format:
```
tolerations:
  - operator: "Exists"
```

**Comment by tamarakaufler** [comment]
I found this complicated format of a nested parameter in consul values.yaml (https://github.com/kubernetes/charts/blob/master/stable/consul/values.yaml):

## nodeAffinity settings
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: cloud.google.com/gke-preemptible
#         operator: NotIn
#         values:
#         - true

**Comment by tamarakaufler** [comment]
A new image with implementation for overriding parameters with list values (containing primitives or aggregates) pushed (quay.io/weaveworks/helm-operator:alpha)

Commit message:

    Extends parameter overriding to those with values in list format
    
        - parameter can be simple (eg image) or a nested one
          (eg resources.requests.memory)
        - parameter value is a list of primitive values or aggregate
          structures (maps, lists) in serialised JSON:
            examples:
            ```
                name: resources.requests.test
                value:  "[{\"A\":\"a\",\"B\":[\"n\",\"o\"]}]"
    
                name: tolerations
                value:
              "[{\"key\":\"aaa\",\"operator\":\"Equal\",\"value\":\"val\",\"effect\":\"NoSchedule\"},{\"key\":\"bbb\",\"operator\":\"Equal\",\"value\":\"val2\",\"effect\":\"NoSchedule\"}]"

**Comment by tamarakaufler** [comment]
The bug fix is now on hold (it is included in the quay.io/weaveworks/helm-operator:alpha image) pending decision about a possible refactoring of the implementation (https://github.com/weaveworks/flux/issues/951. Needs more thought and consideration.). This will be done after the https://github.com/weaveworks/flux/issues/980 is completed.

**Comment by tamarakaufler** [comment]
### Discussion about the format of the overriding spec.values

I am commenting here rather than in #951 as the request for change was made after looking at the bug fix implementation PR. Please see #951 for further details.

#### Synopsis

The current format is:

```
spec:
  ...
  values:
    - name: xxx
      value: yyy
    - name: zzz
      value: aaa
```

where

**name ... parameter name**

Parameter name can take two forms:

  - simple form like `image` or `imageTag`
  - dotted format like `resources.requests.memory` which corresponds to the values.yaml file format:

```
resources:
  requests:
    memory: 256Mi
```

The dotted form was chosen to correspond to the helm client CLI:

      `helm upgrade mongodb-database charts/mongodb --set resources.requests.memory=300Mi`
 
Its simplicity is appealing.

**value ... parameter value**

  - simple value like _bitnami/mongodb:3.7.1-r0_
  - serialised json list like _"[{\"key\":\"AAA\",\"operator\":\"Equal\",\"value\":\"val\",\"effect\":\"NoSchedule\"},{\"key\":\"BBB\",\"operator\":\"Equal\",\"value\":\"val2\",\"effect\":\"NoSchedule\"}]"_ :
     
```
    - name: tolerations
      value:  "[{\"key\":\"AAA\",\"operator\":\"Equal\",\"value\":\"val\",\"effect\":\"NoSchedule\"},{\"key\":\"BBB\",\"operator\":\"Equal\",\"value\":\"val2\",\"effect\":\"NoSchedule\"}]"
```

Most parameters have simple values.

#### FluxHelmRelease resource

Current implementation defines the FluxHelmRelease kind as:

```
type FluxHelmReleaseSpec struct {
	ChartGitPath string           `json:"chartGitPath"`
	ReleaseName  string           `json:"releaseName,omitempty"`
	Values       []HelmChartParam `json:"values,omitempty"`
}

// HelmChartParam ... user customization of Chart parameterized values
type HelmChartParam struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}
```

The newly proposed FluxHelmRelease resource format:

```
type FluxHelmReleaseSpec struct {
	ChartGitPath string                  `json:"chartGitPath"`
	ReleaseName  string                  `json:"releaseName,omitempty"`
	Values       map[string]interface{}  `json:"values,omitempty"`
} 
```
the idea being:
- compacting the spec.values format by removing name and value fields
- the FluxHelmRelease values can take the format of the values.yaml
- no need to process the dotted form into a map.

#### Discussion

It is important to get the FluxHelmRelease format right before helm integration becomes an official part of Flux/Deploy, so we need to carefully consider any implications of the final design.

1. **name and value fields**

Removing these makes FHR manifest more compact. On the other hand as Ilya commented on #951, keyed-list supports patching. If we dont think we need to support patching, then the compact form is preferable.

2. **Helm client format vs values.yaml format**

Helm client CLI uses a dotted format to specify a nested parameter override. values.yaml file takes a yaml map structure.
I believe the dotted format is easier and more compact to provide.

An example of 1. and 2. combined:
```
spec:
  values:
  - resources.requests.memory:  200Mi
  - image: bitnami/mongodb:3.7.1-r0
  - tolerations:
    - key: "key" 
      operator: "Equal" 
      value: "value"
      effect: "NoSchedule"    
``` 

with the FluxHelmRelease kind defined as:

```
type FluxHelmReleaseSpec struct {
	ChartGitPath string                  `json:"chartGitPath"`
	ReleaseName  string                  `json:"releaseName,omitempty"`
	Values       map[string]interface{}  `json:"values,omitempty"`
} 
```
where interface{} represents either a simple value or a list.

3. **Parameters with list values**

A list value can be represented in the as a yaml list or as a serialised json list:

```
 ...
  - tolerations:
    - key: "key" 
      operator: "Equal" 
      value: "value"
      effect: "NoSchedule" 
```
```
 ...
  - tolerations: "[{\"key\":\"AAA\",\"operator\":\"Equal\",\"value\":\"val\",\"effect\":\"NoSchedule\"},{\"key\":\"BBB\",\"operator\":\"Equal\",\"value\":\"val2\",\"effect\":\"NoSchedule\"}]"
```

The current implementation uses the serialised json list form. While majority of parameters from what I have seen in the stable charts repo have simple values, so constructing a serialised json list would be a rare occasion, providing a yaml list feels less strenuous. 

#### Proposal of the new spec.values format

 FluxHelmRelease kind definition:

```
type FluxHelmReleaseSpec struct {
	ChartGitPath string                  `json:"chartGitPath"`
	ReleaseName  string                  `json:"releaseName,omitempty"`
	Values       map[string]interface{}  `json:"values,omitempty"`
} 
```

where the spec.values map contains the following override information:

```
map[string]interface{}
      |        |
      |        |
  parameter name, either simple or dotted format
               |
           parameter value, either simple or a list
```

**Comment by tamarakaufler** [comment]
After team discussion, the following format of the overriding values has been agreed upon:

**FluxHelmRelease kind definition**

```
type FluxHelmReleaseSpec struct {
	ChartGitPath string                  `json:"chartGitPath"`
	ReleaseName  string                  `json:"releaseName,omitempty"`
	Values       map[string]interface{}  `json:"values,omitempty"`
} 
```
**FluxHelmRelease values format**
```
spec:
  values:
    resources:
      requests:
        memory:  200Mi
    image: bitnami/mongodb:3.7.1-r0
    tolerations:
    - key: aaa 
      operator: Equal
      value: 222
      effect: NoSchedule
```
