### ISSUE TITLE
Release images to FluxChartRelease resources

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#985]
`FluxChartRelease` resources are effectively workload controllers, or will usually be, since they will typically

 - refer to a chart that includes at least one core workload controller
 - specify particular images and tags (versions) as `values`

To support release automation, the flux machinery will need to understand how to interpret these resources, and how to update them.

**Comment by tamarakaufler** [comment]
## Investigation

Some possible formats of image info in Helm Chart's values.yaml:

```
image: memcached:1.5.6-alpine
```
```
image: itzg/minecraft-server
imageTag: latest
```
```
image:
  repository: quay.io/monax/db
  tag: 0.17.1
```
```
image:
  registry: docker.io
  repository: bitnami/mariadb
  tag: 10.1.32
```
```
artifactory:
  image:
    repository: "docker.bintray.io/jfrog/artifactory-pro"
    version: 5.9.1
```
```
jupyter:
  image:
    repository: "daskdev/dask-notebook"
    tag: "0.17.1"
```
